services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: 'unless-stopped'
    user: 1000:100
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    volumes:
      - ~/homelab-data/jellyfin/config:/config
      - ~/homelab-data/jellyfin/cache:/cache
      - type: bind
        source: ~/media
        target: /media
        read_only: true
  database:
    image: postgres:18
    container_name: database
    restart: 'unless-stopped'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: mealie
      PGUSER: ${POSTGRES_USER}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 20s
      retries: 3
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v3.28.0
    container_name: mealie
    restart: 'unless-stopped'
    ports:
        - "9000:9000" 
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - mealie_data:/app/data/
    environment:
      # Set Backend ENV Variables Here
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 100
      TZ: Europe/Paris
      #BASE_URL: https://mealie.yourdomain.com don't have a domaine now do i need one ?
      # Database Settings
      DB_ENGINE: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_SERVER: database
      POSTGRES_PORT: 5432
      POSTGRES_DB: mealie
    depends_on:
      database:
        condition: service_healthy

volumes:
  postgres_data:
  mealie_data:
